fix: add missing await
typeorm/typeorm pull request #10084
Opened 2023-05-27 21:04 UTC by pro100kryto

### Description
There are missing `await` that cause `QueryRunnerAlreadyReleasedError`.

### Pull-Request Checklist

- [ X ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ X ] This pull request links relevant issue  [MigrationExecutor - Query runner already released. #10083](https://github.com/typeorm/typeorm/issues/10083)
- [ ] There are new or updated unit tests validating the change
- [ N/A ] Documentation has been updated to reflect this change
- [ X ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2023-06-12 15:31 UTC, maixuanhan requested changes
This does not help since the function can return a Promise.

2023-06-19 16:27 UTC, nikolay-mironov-trasa commented
In my case, it helped me to fix the bug.
I made an script that put missing `await` after a package installation (`npm install`) and it does work.

2023-06-19 16:29 UTC, pro100kryto commented
In my case, it helped me to fix the bug.
I made an hotfix script that put missing await after the packages installation (npm install) and it does work.

2023-06-19 18:10 UTC, merged

2023-06-19 18:10 UTC, pleerock commented
Thank you for contribution! 🎉