fix: A bug fix for QueryDeepPartialEntity type definition to allow pr…
typeorm/typeorm pull request #10156
Opened 2023-06-27 00:38 UTC by vsamofal-sk

### Description of change

Fixes #10155

I verified it by pulling this branch into my project and experimenting with a change. Now inheritance works properly 

### Pull-Request Checklist

- [ x ] Code is up-to-date with the `master` branch
- [ x ] `npm run format` to apply prettier formatting
- [ N/A ] `npm run test` passes with this change (can't run on M1)
- [ ] This pull request links relevant issues as `Fixes #10155`
- [ N/A ] There are new or updated unit tests validating the change (I don't think any new tests are needed, it just types) 
- [ N/A ] Documentation has been updated to reflect this change
- [ x ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2023-07-09 17:09 UTC, hinogi commented on src/query-builder/QueryPartialEntity.ts
> +    T extends "toString" ? T : unknown
For me it seems like

```ts
/**
 * Make all properties in T optional
 */
export type QueryPartialEntity<T> = {
    [P in keyof T]?: T[P] | (() => string)
}
```

could be an issue.
I would have expect something like

```ts
/**
 * Make all properties in T optional
 */
export type QueryPartialEntity<T> = {
    [P in keyof T]?: QueryPartialEntity<T[K]>
}
```

for Deep partial objects, or the long version

```ts
interface DeepPartialArray<T> extends Array<DeepPartial<T>> {}

export type QueryPartialEntityObject<T> = {
    [P in keyof T]?: QueryPartialEntity<T[K]>
}
export type QueryPartialEntity<T> = T extends Function
  ? T
  : T extends Array<infer InferredArrayMember>
  ? DeepPartialArray<InferredArrayMember>
  : T extends ObjectLiteral
  ? QueryPartialEntityObject<T>
  : T | undefined;
```

props to @mattpocockuk

https://www.youtube.com/watch?v=AhzjPAtzGTs

2023-07-09 17:11 UTC, hinogi requested changes
I think the QueryPartialEntity needs some work first, or the comment needs more precision on what kind of partial object is expected and what members it could have

2023-08-02 04:24 UTC, kusigit commented
`[ N/A ] npm run test passes with this change (can't run on M1)`

You have to enable `Use Rosetta for x86/amd64 emulation on Apple Silicon` in the Docker settings `Features in development`.

2024-01-02 09:13 UTC, pleerock commented
I didn't get the purpose of these changes based on the issue description. Let's see if others report back the same issue. Closing for now.

2024-01-02 09:13 UTC, closed without merging

2024-11-22 15:45 UTC, cameron-hicks commented
@pleerock would you be open to revisiting this bugfix? I'm having a bug similar to https://github.com/typeorm/typeorm/issues/9826 and @hinogi's suggestion seems to fix it.