feat: Add an option to disable `cli-highlight` usage
typeorm/typeorm pull request #10221
Opened 2023-07-20 12:53 UTC by netroy

### Description of change

While cli highlighting can be a very useful tool, the package `cli-highlight` has a handful of issues for us:
1. The library seems abandoned, and a potential security issue waiting to happen.
2. When loading typeorm, over 30% of the code loaded into memory is coming from `cli-highlight` and its dependencies.

Just as how typeorm lazy-loads all drivers, It makes sense to do so for `cli-highlight` as well, optionally giving users the choice to not load this library at all.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2023-07-25 23:39 UTC, netroy commented
@pleerock I'm curious if this change makes sense to typeorm maintainers? 
for more context: we run thousands of instances of an application where this package contributes to over 5% in baseline memory usage, and at our scale those memory savings can often lead to more infrastructure capacity.
But, I also understand that this wouldn't be relevant to most other users. so, I wanted to check with you if we should consider maintaining a patch/fork instead, as we'd really like to stop loading `cli-highlight` package in our application.

2023-08-08 17:14 UTC, kusigit commented
It would be good to write a note in the [documentation](https://github.com/typeorm/typeorm/blob/master/docs/logging.md) about the new environment variable `DISABLE_CLI_HIGHLIGHT`.

2023-08-13 15:14 UTC, hinogi requested changes
> It would be good to write a note in the [documentation](https://github.com/typeorm/typeorm/blob/master/docs/logging.md) about the new environment variable `DISABLE_CLI_HIGHLIGHT`.

I second that. Docs missing.

2023-08-22 18:29 UTC, closed without merging

2024-01-16 16:30 UTC, mkilp commented
Fair point, thanks for the heads-up. I will cherry pick these and open my own PR.

2024-01-16 16:36 UTC, netroy commented
Since `cli-highlight` looks abandoned, I'd rather recommend ripping it out instead of adding an option to disable it.

2024-01-16 16:50 UTC, mkilp commented
I have it out in my local repo right now and test in our systems first. I might raise a PR with the change - seems like a luxury library to begin with.