Add BeforeQuery and AfterQuery events
typeorm/typeorm pull request #10234
Opened 2023-07-26 16:31 UTC by mnguyen081002

Fixes https://github.com/typeorm/typeorm/issues/3302 (see https://github.com/typeorm/typeorm/issues/3302#issuecomment-449422542)
### Description of change

This PR adds BeforeQuery and AfterQuery events, which provide data about the queries run against the database immediately before and after execution. The events include the raw queries and parameters, and, for the AfterQuery event, the success status, raw result, execution time and possible error.

This feature enables better integration with a wide range of providers, such as logging and tracing utilities. Although similar functionality exists with custom loggers, only one custom logger can be used at once making multiple integrations cumbersome. Additionally, access to the query execution time is available for all queries only after manually setting [maxQueryExecutionTime: -1](https://orkhan.gitbook.io/typeorm/docs/logging#log-long-running-queries) -- setting this config value incorrectly could cause unexpected behavior with external connections.

I'm submitting this PR as a WIP for now to get feedback on my implementation as I finish updating the tests and documentation. If anyone has a better solution in mind, I'm open to suggestions!

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2023-08-13 10:07 UTC, hinogi commented on src/driver/mysql/MysqlQueryRunner.ts
> +                    async (err: any, raw: any) => {
since this function seems to return something. Switching from sync to async may cause a problem since it will now always return a promise.

2023-08-13 10:10 UTC, hinogi commented on src/driver/sap/SapQueryRunner.ts
> +        } catch (err) {
Good catch of the bad naming 👍

2023-08-13 10:15 UTC, hinogi requested changes
Double check on changing sync to async where something is returned. The change may have side effect or will cascade.

2023-08-17 08:51 UTC, hinogi commented
https://github.com/typeorm/typeorm/pull/10067 is this the same?

2023-08-17 17:26 UTC, mnguyen081002 commented
> is this the same?

Yes, it appears to be the same

2024-01-02 07:23 UTC, merged

2024-01-02 07:23 UTC, pleerock commented
Thank you for contribution! 🎉