feat: Postgres @Tree specify schema for closure tables
typeorm/typeorm pull request #10743
Opened 2024-02-28 09:57 UTC by andimattes

### Description of change

Adds `closureTableSchema` to `ClosureTreeOptions` to define the schema of the closure table.

Closes: #10263

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2024-03-01 11:27 UTC, monrostar commented
I would like to get this fix into the new version of Typeorm as soon as possible because we have a table with these relationships that cause a problem when using `relationLoadStrategy: 'query'`

My current error that we need to bypass in every query manually right now
```bash
Error: table name "Collection" specified more than once
```

2025-01-21 13:55 UTC, gioboa reviewed
Thanks @andimattes for your help.
I added this PR to our release board

2026-01-04 13:52 UTC, gioboa reviewed
@andimattes Can I ask you to solve the conflicts please?

2026-01-15 21:32 UTC, alumni commented
@andimattes thanks for this contribution!

Could you please ~fix the merge conflicts,~ rename the test file to end with `.test.ts` and fix the lint error?

Also, I'm wondering whether the schema should not be inherited from the entity. Basically, I'm thinking the priority should be `treeOptions.closureTableSchema` (if we want to keep it), `entityOptions.schema`, `dataSourceOptions.schema`.

2026-01-17 12:57 UTC, gioboa reviewed
> Could you please rename the test file to end with .test.ts and fix the lint error?

I did it, let's see if tests are passing 🤞

2026-01-17 13:31 UTC, gioboa approved these changes
Thanks @andimattes for your help.

> Also, I'm wondering whether the schema should not be inherited from the entity. Basically, I'm thinking the priority should be treeOptions.closureTableSchema (if we want to keep it), entityOptions.schema, dataSourceOptions.schema.

Can you address or answer at this feedback from @alumni please?

2026-02-24 16:26 UTC, gioboa requested changes
Can you address or answer at this feedback from @alumni please?

2026-06-19 12:16 UTC, alumni commented
@andimattes Thanks for the contribution - I will close the PR since it was stale and the idea was picked up and improved in #12590

2026-06-19 12:16 UTC, closed without merging