Fix documentation links
typeorm/typeorm pull request #10871
Opened 2024-05-02 11:41 UTC by juherr

### Description of change

Fix links

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2025-01-05 20:48 UTC, michaelbromley requested changes
The changes to the anchors links seem to be wrong. Can you verify this?

2025-01-05 20:48 UTC, michaelbromley commented on docs/data-source-options.md
> +-   [`mysql` / `mariadb` data source options](#mysql-mariadb-data-source-options)
The original anchor link works. This update breaks it.

2025-01-05 20:48 UTC, michaelbromley commented on docs/data-source-options.md
> +-   [`postgres` / `cockroachdb` data source options](#postgres-cockroachdb-data-source-options)
Same here.

2025-01-19 21:18 UTC, gioboa requested changes
Thanks for looking at this project @juherr 
I think we can close this PR because these links are working fine in the current doc website.

2025-01-20 06:51 UTC, closed without merging

2025-01-20 12:42 UTC, juherr commented
@gioboa Anchors are still broken for mysql and postgress.

See https://orkhan.gitbook.io/typeorm/docs/data-source-options

Current is broken:
https://orkhan.gitbook.io/typeorm/docs/data-source-options#mysql--mariadb-data-source-options

Expected is working:
https://orkhan.gitbook.io/typeorm/docs/data-source-options#mysql-mariadb-data-source-options

2025-01-20 13:29 UTC, gioboa commented
I think it's related to your domain / stack, in fact if you click here 
https://typeorm.io/data-source-options#mysql--mariadb-data-source-options
it's working fine

2025-01-20 13:56 UTC, juherr commented
@gioboa Got it! It is working from typeorm.io but failing from orkhan.gitbook.io