fix: EntityManager update/delete/softDelete don't work with list of w…
typeorm/typeorm pull request #10910
Opened 2024-05-29 12:46 UTC by maxbronnikov10

### Description of change

Fixes #10517

### Pull-Request Checklist
- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2025-01-30 06:46 UTC, maxbronnikov10 commented
@michaelbromley hello, sorry for tag, can u check this PR please? I think it is quite simple

2025-04-21 17:42 UTC, maxbronnikov10 commented
@alumni hi! can u pls check PR?

2025-04-24 22:25 UTC, maxbronnikov10 commented
@naorpeled hello! Can u check this PR please?

2025-05-01 18:58 UTC, maxbronnikov10 commented
@sgarner hello! Can u check this PR please?

2025-05-01 22:07 UTC, sgarner reviewed
This is a nice fix, thanks @maxbronnikov10 !

One suggestion, otherwise looks good

2025-05-01 22:07 UTC, sgarner commented on src/entity-manager/EntityManager.ts
> +                criteria[0] !== null)
I would prefer that the type check on the array element matches the type check on a single value, i.e. we should specifically allow the array to contain only elements which are 'string or number or Date' rather than containing anything that's 'not an object or null'.

For bonus points, it would be nice to abstract this logic... Something like the following could be added to OrmUtils and re-used across all these checks:

```ts
static isIdType(value: unknown): value is string | number | Date {
    return (
        typeof value === "string" ||
        typeof value === "number" ||
        value instanceof Date
    )
}

static isIdTypeOrList(value: unknown): value is string | number | Date | (string | number | Date)[] {
    if (Array.isArray(value)) {
        return value.every((el) => this.isIdType(el))
    }

    return this.isIdType(value)
}
```

2025-05-02 00:44 UTC, maxbronnikov10 commented on src/entity-manager/EntityManager.ts
> +                criteria[0] !== null)
fix done
i also added type alias for `string | number | Date` and organized OrmUtils(private methods at the bottom of file)

2025-05-02 01:09 UTC, maxbronnikov10 commented on src/entity-manager/EntityManager.ts
> +                criteria[0] !== null)
omg i forgot run formatting, commited again, sorry

2025-05-02 01:58 UTC, sgarner approved these changes
Couple more suggestions, otherwise LGTM :+1:

2025-05-02 01:58 UTC, sgarner commented on src/util/OrmUtils.ts
> +    public static isCriteriaNullOrEmpty(criteria: unknown): boolean {
This could be named `isNullOrEmpty` to allow for broader use?

2025-05-02 01:58 UTC, sgarner commented on src/util/OrmUtils.ts
> +    private static isSinglePrimitiveCriteria(
I think this could be made public, even if we're not using it anywhere else yet.

2025-05-02 02:17 UTC, maxbronnikov10 commented on src/util/OrmUtils.ts
> +    public static isCriteriaNullOrEmpty(criteria: unknown): boolean {
specifically made it with prefix "criteria" based on my experience that each class have own set of nullish values
but i can rewrite this if u not same opinion

2025-05-02 02:17 UTC, maxbronnikov10 commented on src/util/OrmUtils.ts
> +    private static isSinglePrimitiveCriteria(
good
i will be change it after commitment in previous comment - for run tests once

2025-05-02 02:27 UTC, sgarner commented on src/util/OrmUtils.ts
> +    public static isCriteriaNullOrEmpty(criteria: unknown): boolean {
Occurs to me now that this method ought to also check if an empty object (`Object.keys(criteria).length === 0`) is passed?

If we cover all those bases then this seems like a pretty good generic definition of "empty". But you make a fair point as well, so the current name is acceptable if you want to keep it.

2025-05-02 02:36 UTC, maxbronnikov10 commented on src/util/OrmUtils.ts
> +    public static isCriteriaNullOrEmpty(criteria: unknown): boolean {
yeah u right, object without keys also not valid

2025-05-02 02:57 UTC, sgarner requested changes

2025-05-02 02:57 UTC, sgarner commented on src/util/OrmUtils.ts
> +            Object.keys(criteria).length === 0
To be safe:
```suggestion
            (typeof criteria === 'object' && Object.keys(criteria).length === 0)
```

2025-05-02 03:41 UTC, sgarner approved these changes

2025-05-03 18:45 UTC, jovanadjuric approved these changes

2025-05-04 16:38 UTC, mguida22 approved these changes
This is great, thanks for the contribution!

Two things that don't need to block merging this PR:
 - Since this is more of a core functionality that we want to support as opposed to a regression, I think these tests would be best under our [functional tests](https://github.com/typeorm/typeorm/tree/master/test/functional/).
 - A separate PR to update the docs to show examples of this functionality will help let people know this is possible now.

2025-05-04 16:38 UTC, mguida22 commented on src/util/OrmUtils.ts
> +    public static isSinglePrimitiveCriteria(
Can you add a docstring comment for each of these new functions?

2025-05-04 16:38 UTC, mguida22 commented on src/util/OrmUtils.ts
> +                OrmUtils.isSinglePrimitiveCriteria(value),
nit: IMO it's more clear to use `this` when calling methods on this class. There's a few more in these changes
```suggestion
                this.isSinglePrimitiveCriteria(value),
```

2025-05-06 02:05 UTC, sgarner approved these changes
LGTM

Let us know if you want to address @mguida22 's feedback in this PR, or merge and follow up separately.

2025-05-06 21:14 UTC, maxbronnikov10 commented
> Collaborator

yeap, i want to merge now and add tests, docs in separated PR

2025-05-06 21:29 UTC, mguida22 commented
> Thanks! I want to merge now and add tests, docs in separated PR

Created this issue to track the docs updates https://github.com/typeorm/typeorm/issues/11447

2025-05-06 21:30 UTC, merged

2025-05-13 07:15 UTC, christian-forgacs commented
![CleanShot 2025-05-13 at 09 08 46](https://github.com/user-attachments/assets/932bebf3-f73b-45b5-afc9-99fff059392f)

Is this behavior intentional? In our project, we actually handle exactly these cases and explicitly throw an exception to prevent any unintended side effects.

2025-05-13 09:03 UTC, sgarner commented
> Is this behavior intentional? In our project, we actually handle exactly these cases and explicitly throw an exception to prevent any unintended side effects.
> 
> ```ts
> console.log(isCriteriaNullOrEmpty({id: undefined})); // false > not empty
> console.log(isCriteriaNullOrEmpty([{}])); // false > not empty
> console.log(isCriteriaNullOrEmpty([{id: undefined}])); // false > not empty
> ```

The array containing only empty objects is interesting. Probably we should catch that one. :confused:

There is other work in progress regarding handling of undefined values: https://github.com/typeorm/typeorm/pull/11332