docs: add performance and optimizing
typeorm/typeorm pull request #11068
Opened 2024-09-18 11:44 UTC by ngxquang

### Description of change

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2025-01-20 14:11 UTC, gioboa requested changes

2025-01-20 14:11 UTC, gioboa commented on docs/performance-optimizing.md
> +- Lazy loading loads the relation data only when needed, reducing database load when all related data isn't always necessary.
Thanks @ngxquang for your help.
I think is good to have links to the specific doc pages (in this case https://typeorm.io/eager-and-lazy-relations#lazy-relations) to have a whole description on the topic.
This suggestion is for all the tips you added. Nice job :muscle:

2025-01-22 14:06 UTC, ngxquang commented on docs/performance-optimizing.md
> +- Lazy loading loads the relation data only when needed, reducing database load when all related data isn't always necessary.
Thanks for the feedback! I've updated the documentation to include the lazy and eager relations links. Let me know if there's anything else you'd like adjusted!

2025-01-22 15:33 UTC, gioboa approved these changes
This is a nice piece of documentation, really clear and straight to the point.
Thanks @ngxquang for your help
I added this PR in our release board

2025-02-06 13:31 UTC, albasyir approved these changes

2025-02-14 20:16 UTC, merged