fix: beforeQuery promises not awaited before query execution
typeorm/typeorm pull request #11086
Opened 2024-10-04 10:45 UTC by TanguyPoly

Closes: #11085

### Description of change

Now awaiting `broadcasterResult.wait()` before query execution, so that `beforeQuery` promises are executed before query execution

I added a new test to verify that  `beforeQuery` promise is awaited before query run

### Pull-Request Checklist

- [ X] Code is up-to-date with the `master` branch
- [ X] `npm run format` to apply prettier formatting
- [ X] `npm run test` passes with this change
- [ X] This pull request links relevant issues as `Fixes #0000`
- [ X] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change -> N/A
- [ X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2024-11-26 15:14 UTC, amiryadid commented
@TanguyPoly Did you reach out to anyone for reviewing and merging this?

2024-12-02 17:01 UTC, TanguyPoly commented
@amiryadid No i did not, I used a workaround in the mean time (extending repository methods, using the same name and then calling the original method via the entityManager, did the same for the createQueryBuilder)

2025-03-04 23:17 UTC, alumni commented on src/driver/sap/SapQueryRunner.ts
> +            await broadcasterResult.wait()
Hmmm, isn't

```ts
this.broadcaster.broadcastBeforeQueryEvent(
    broadcasterResult,
    query,
    parameters,
)

await broadcasterResult.wait()
```
equivalent to:
```ts
await this.broadcaster.broadcast("BeforeQuery", query, parameters)
```
?

I'm also wondering why do we have to use `BroadcasterResult` at all. We could also slightly change the try-catch block and we'd be able to simply call `Broadcaster.broadcast` also for `AfterQuery`.

Were we using `BroadcasterResult` because maybe we thought that the listeners might throw?

2025-03-05 01:39 UTC, sgarner reviewed
In `query()` methods, the `BroadcasterResult` is shared between multiple events 
 - BeforeQuery and AfterQuery. It is used to sum up and wait for the promises of all the subscribers across both events.

This is why `await broadcast()` is not used currently, because that only broadcasts a single event.

Adding a call to `wait()` on the broadcastResult before query execution means any promises returned from BeforeQuery subscribers will be resolved twice - once there, and once again after the query finishes. This may not have any noticeable effect, but... it smells a bit off to me.

It looks like the current implementation is not intended to allow BeforeQuery subscribers to complete before the query is executed, but rather for them to be executed in parallel with the query. The `BroadcastResult` is used for error handling, and perhaps to ease debugging.

As @alumni suggested the code could be revised to `broadcast()` the BeforeQuery event separately, wait for it before executing the query, and not share a `BroadcastResult` with the AfterQuery event. This _might_ be a breaking change though. I wonder what the use cases are for BeforeQuery subscribers returning promises?

2025-03-05 01:54 UTC, sgarner commented
I just read the linked issue and original PR which added these events. Now I'm inclined to think that the execution of 'before' subscribers in parallel with the query is just a bug.

In other contexts we do already await 'before' subscribers, e.g.
https://github.com/typeorm/typeorm/blob/513be336c863d5da49aa933806b17e3c95e83754/src/persistence/SubjectExecutor.ts#L111

So I agree with @alumni suggestion to use `await broadcast()`

2025-03-05 21:17 UTC, sgarner commented
> It's definitely a bug (there's no breaking change in this PR), I was just thinking a bit more about the exception handling :)

What I meant was, if any users are relying on the current behavior of BeforeQuery subscribers executing in parallel with the query, if we change this to happen in series then the behavior of their application may also be subtly changed.

But, since this behavior was not documented and may have originally been unintentional, I think we can say this was an implementation detail that shouldn't be relied upon, and therefore it isn't a breaking change.

> Not all drivers behave identically though, e.g. `CockroachQueryRunner` and `CordovaQueryRunner` have correct exception handling: `this.connect()` and `broadcastBeforeQueryEvent` are outside of the `try-catch-finally` block - this should probably happen for other drivers too.

The AfterQuery event interface includes properties for an error and success boolean, so they're clearly meant to be triggered in case of failure. It may be useful for that to include connection errors. But triggering AfterQuery for an error in the BeforeQuery subscribers probably makes less sense? Whichever way, it should certainly be made consistent between drivers.

Should `broadcast()` happen first, outside the try/catch, and then `connect()` inside it?

2025-03-05 21:26 UTC, sgarner commented
No, actually... we can't do that because if the user wants to execute their own queries inside the BeforeQuery subscriber, the provided QueryRunner won't be connected yet.

So we either:

1. Put everything inside the try/catch and accept that AfterQuery subscribers trigger on errors in the BeforeQuery subscribers
2. Put `broadcast('BeforeQuery')` and `connect()` outside the try/catch and accept that AfterQuery subscribers won't trigger for connection errors

2025-03-05 21:37 UTC, alumni commented
> 2\. Put `connect()` and `broadcast('BeforeQuery')` outside the try/catch and accept that AfterQuery subscribers will no longer trigger for connection errors

Exactly. This is what I am suggesting above. This is how CockroachDB does it, but not SAP (did not check more drivers).

2025-03-05 21:53 UTC, sgarner commented
> Exactly. This is what I am suggesting above. This is how CockroachDB does it, but not SAP (did not check more drivers). Then the events will be triggered correctly and the errors should be handled correctly.

OK, I looked through and found the following for `connect()` and broadcast of BeforeQuery events:

- ✅ BetterSqlite3QueryRunner does it outside the try/catch
- ✅ CockroachQueryRunner does it outside the try/catch
- ✅ CordovaQueryRunner does it outside the try/catch
- ✅ PostgresQueryRunner does it outside the try/catch
- ✅ OracleQueryRunner does it outside the try/catch
- ✅ SapQueryRunner does it outside the try/catch
- 🙅 ExpoQueryRunner does it inside the try/catch
- 🙅 MysqlQueryRunner does it inside the try/catch
- 🙅 ReactNativeQueryRunner does it inside the try/catch
- 🙅 SpannerQueryRunner does it inside the try/catch
- 🙅 SqlServerQueryRunner does it inside the try/catch
- 😕 SqliteQueryRunner broadcasts BeforeQuery event outside, then connects inside the try/catch
- 😕 SqljsQueryRunner broadcasts BeforeQuery event outside, doesn't connect() at all
- ❌  AuroraMysqlQueryRunner doesn't trigger BeforeQuery/AfterQuery events at all
- ❌  AuroraPostgresQueryRunner doesn't trigger BeforeQuery/AfterQuery events at all
- ❌  CapacitorQueryRunner doesn't trigger BeforeQuery/AfterQuery events at all
- ❌  MongoQueryRunner doesn't trigger BeforeQuery/AfterQuery events at all
- ❌  NativeScriptQueryRunner doesn't trigger BeforeQuery/AfterQuery events at all

2025-03-11 13:17 UTC, alumni commented
@amiryadid @TanguyPoly I would adjust the logic in the drivers to be the same everywhere - @sgarner made that nice overview above. The drivers marked with 🙅 and 😕 should behave similarly to the ones marked with ✅, i.e.:
  - `Broadcaster.broadcast("BeforeQuery")`
  - `connect()`
  - `new BroadcastResult()` (used only for AfterQuery)
  - `try`: execute `query`; `broadcastAfterQueryEvent(broadcastResult, result)`
  - `catch`: `broadcastAfterQueryEvent(broadcastResult, error)`
  - `await broadcastResult.wait()`

Regarding an ETA: we will have more regular releases, so when the PRs are ready (reviewed, approved and don't have breaking changes), they will be merged and released in the next release. If you want to contribute with something, I would say you can do it with code (PRs) 🙂

2025-03-11 16:23 UTC, amiryadid commented
@TanguyPoly do you think you'll have the time to implement the above-mentioned changes?
I'm personally on a tighter schedule ATM + will have overhead of learning the codebase, so if it's problematic for you to implement LMK and I'll try to squeeze that in perhaps.

BTW no pressure on that ETA, just asked out of curiosity, I'm sure this repo is a handful 🙂

2025-03-11 16:35 UTC, TanguyPoly commented
Hello everyone !

@amiryadid Yes sure i can have a look at it this week i think, I should be able to dedicate some time to it.

Thank you @sgarner & @alumni for taking the time to review & make suggestions ! :pray:

2025-03-15 22:02 UTC, TanguyPoly commented
I did the changes to all drivers with 🙅 & 😕 except the `SqljsQueryRunner` driver because it doesn't have a `connect` method unlike other drivers

2025-03-20 23:31 UTC, TanguyPoly commented on src/driver/cordova/CordovaQueryRunner.ts
> +            await broadcasterResult.wait()
Yes done !

2025-03-20 23:34 UTC, TanguyPoly commented on src/driver/sap/SapQueryRunner.ts
> +            await broadcasterResult.wait()
Sorry i didn't understood well this comment and missed the requested changes, thank you for applying them in your commits :pray:

2025-03-21 10:33 UTC, alumni approved these changes

2025-03-21 13:22 UTC, alumni commented on src/driver/sap/SapQueryRunner.ts
> +            await broadcasterResult.wait()
Ah, I thought because of the types 😅 I also had to fix the types for the two events that we care about in this PR.

Basically, I wanted to avoid the same `BroadcastResult` for two different events.

2025-04-15 07:17 UTC, amiryadid commented
Hey y'all 🙂
Noticed this was approved but not merged and now it has a few additional conflicts.
@TanguyPoly do you need assistance in resolving them?
I just don't want this PR to go stale when it's borderline merged

2025-04-15 12:37 UTC, TanguyPoly commented
@amiryadid Hello, the conflicts have been resolved, and i guess it will be merged when 2 reviewers will have approved this merge requested (i only had one approval until the conflict, hence why it was not merged before).

2025-04-16 16:24 UTC, alumni approved these changes

2025-04-16 16:34 UTC, gioboa approved these changes

2025-04-16 22:50 UTC, sgarner requested changes

2025-04-16 22:50 UTC, sgarner commented on src/driver/mysql/MysqlQueryRunner.ts
>              try {
I know it is existing code not introduced in this PR, but we have some weird construction in this method (and replicated in some other QueryRunner classes similar to this one).

Firstly, returning a `new Promise()` is unnecessary in an `async` function. Then the weirdness is doubled by using an `async function` as the Promise executor: `new Promise(async (ok, fail) => {...})`.

I am concerned that moving `await this.connect()` inside this async Promise executor means that database connection errors will now be lost; an error here won't cause the Promise to reject, but it will never resolve, likely causing a hang.

Ideally the code should be rewritten as proper async/await style without `new Promise()`. Alternatively, the connection and before-query code should be moved outside of the Promise executor, or another try/catch block added to handle errors in this code.

2025-04-16 22:50 UTC, sgarner commented on src/subscriber/Broadcaster.ts
> +    ) => void
For readability prefer to write `undefined` last in type unions, so the expected type is first:

```suggestion
    BeforeQuery: (query: string, parameters: any[] | undefined) => void
    AfterQuery: (
        query: string,
        parameters: any[] | undefined,
        success: boolean,
        executionTime: number | undefined,
        rawResults: any | undefined,
        error: any | undefined,
    ) => void
```

2025-04-18 08:26 UTC, TanguyPoly commented on src/driver/mysql/MysqlQueryRunner.ts
>              try {
Good catch ! I've rewritten the code to get rid of them

2025-04-19 07:55 UTC, TanguyPoly commented
I tried to run the sqlite tests locally but most of them failed with a "Segmentation fault" as mentioned here: https://github.com/typeorm/typeorm/issues/10212

I was still able to run some of them and see that the issues seems to be fixed

2025-04-19 13:21 UTC, alumni commented
@sgarner @TanguyPoly what if we revert to the last commit where the tests where passing and merge this PR? There are quite a lot of changes, if we need to do something else, we can do it separately.

2025-04-19 22:40 UTC, sgarner commented
> @sgarner @TanguyPoly what if we revert to the last commit where the tests were passing and merge this PR? There are quite a lot of changes, if we need to do something else, we can do it separately.

Yes it looks like rewriting the query Promises is adding too much extra complexity here (mysql is broken as well as sqlite) and that effort would be better tackled in its own PR. But, it's not ideal to merge a PR with known bugs either.

@TanguyPoly let's revert the Promise changes back out. We still need to handle connection errors though, how about adding try/catch blocks instead?

2025-04-21 11:50 UTC, TanguyPoly commented
@sgarner Yes i can revert the changes and add try / catch blocks instead, seems to be a good option for the time being :+1:

2025-04-29 08:17 UTC, TanguyPoly commented
@sgarner Everything should be good now, it would be great if ths pr can be approved before having to solve other conflicts with master, thank you 🙏

2025-04-29 21:41 UTC, sgarner approved these changes
LGTM

Thanks very much for all your effort on this @TanguyPoly 🧡

2025-04-30 21:16 UTC, merged