feat: add new foreign key decorator
typeorm/typeorm pull request #11144
Opened 2024-11-24 16:26 UTC by yevhen-komarov

This new feature change the behavior of typeorm to allow the use new foreign key decorator (@ForeignKey) to create foreign key constraint without relation.

Closes: #4569

### Description of change

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2024-12-15 10:26 UTC, yevhen-komarov commented
@michaelbromley @OSA413 What else do I need to do to get PR reviewed and merged?

2024-12-15 17:15 UTC, OSA413 commented
If I understand correctly, currently we are focusing on stabilizing existing things, later we will look at new features.

First we need to create the new features board to triage all new features, so it will take some time, probably.

2025-03-16 12:41 UTC, OSA413 requested changes

2025-03-16 12:41 UTC, OSA413 commented on src/decorator/ForeignKey.ts
> +export function ForeignKey<T>(
Can you please add `ForeignKey` into the shim?
https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js

2025-03-16 12:42 UTC, OSA413 commented
I would also add a test for `repository.find` to see what actually happens when the decorator is used in other use cases.

2025-03-17 13:41 UTC, yevhen-komarov commented on src/decorator/ForeignKey.ts
> +export function ForeignKey<T>(
Done.

2025-03-17 13:42 UTC, yevhen-komarov commented
> I would also add a test for `repository.find` to see what actually happens when the decorator is used in other use cases.

Done.

2025-03-18 21:05 UTC, sgarner commented
What will happen when users inevitably misunderstand the purpose of this feature and apply `@ForeignKey` together with `@ManyToOne` etc? Perhaps it should customise the relation's automatically generated foreign key, or produce an error in this case.

I have to say I don't really see the value in this feature. What possible use cases are there for defining a foreign key but not defining the relationship that it represents?

2025-03-19 05:06 UTC, yevhen-komarov commented
> What will happen when users inevitably misunderstand the purpose of this feature and apply `@ForeignKey` together with `@ManyToOne` etc? Perhaps it should customise the relation's automatically generated foreign key, or produce an error in this case.

If you do it like this:
```typescript
    @Column()
    @ForeignKey("cities")
    dispatchCityId: number

    @ManyToOne(() => City)
    dispatchCity: City
```

there will be a driver error, something like:
driverError: error: constraint "FK_499c98d1ec465d0b4de2da9744c" for relation "orders" already exists

2025-03-19 05:35 UTC, yevhen-komarov commented
> I have to say I don't really see the value in this feature. What possible use cases are there for defining a foreign key but not defining the relationship that it represents?

There really aren't many use cases, but at least there is a issue #4569.

I needed to relate tables with foreign key on two fields, but use a relationship on one unique:
```typescript
@Entity('orders')
export class Order {

  @Column('uuid', { nullable: true })
  settlementRef: string | null;

  @ManyToOne(() => Settlement)
  settlement: Settlement | null;

  @Column('uuid', { nullable: true })
  warehouseRef: string | null;

  @ManyToOne(() => Warehouse)
  warehouse: Warehouse | null;

}

@Entity('orders')
export class OrderFK extends Order {
  @ManyToOne(() => Warehouse, { nullable: true })
  @JoinColumn([
    { name: 'warehouse_ref', referencedColumnName: 'ref' },
    { name: 'settlement_ref', referencedColumnName: 'settlementRef' },
  ])
  warehouseFK: Warehouse | null;
}
```
Why is it so difficult? Two similar connections lead to a messes up the query builder, see #11132

With `@ForeignKey` we can make it easier
```typescript
@Entity('orders')
@ForeignKey(() => Warehouse, ["warehouseRef", "settlementRef"], ["ref", "settlementRef"])
export class Order {

  @Column('uuid', { nullable: true })
  settlementRef: string | null;

  @ManyToOne(() => Settlement)
  settlement: Settlement | null;

  @Column('uuid', { nullable: true })
  warehouseRef: string | null;

  @ManyToOne(() => Warehouse)
  warehouse: Warehouse | null;

}
```

2025-03-19 21:12 UTC, sgarner commented
> there will be a driver error, something like:
driverError: error: constraint "FK_499c98d1ec465d0b4de2da9744c" for relation "orders" already exists

Right, of course... I suppose that's sufficient.

> There really aren't many use cases, but at least there is a issue #4569.

Yes I read the linked issue, but it seemed that people were just being a bit precious about defining a relation property that they won't use. The [workaround](https://github.com/typeorm/typeorm/issues/4569#issuecomment-1021160630) of making such properties `private` and non-persisted is a reasonable one IMO.

Your example schema is quite a convoluted structure, but I understand we are forced to work with such database designs sometimes. It does demonstrate a more practical case for this feature.

2025-03-19 21:13 UTC, sgarner requested changes
The test doesn't establish whether a foreign key is created correctly. Could we have another test for this? Similar to:
https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/indices/indices-create-modify.ts

I'm suggesting some doc changes to make clear that this new decorator isn't for everyday use, otherwise LGTM.

Thanks for your contribution 💙

2025-03-19 21:14 UTC, sgarner requested changes

2025-03-19 21:14 UTC, sgarner commented on src/decorator/ForeignKey.ts
> + * Creates a database foreign key. Can be used on entity property or on entity.
```suggestion
 * Creates a database foreign key. Can be used on entity property or on entity.
 * Can create foreign key with composite columns when used on entity.
 * Warning! Don't use this with relations; relation decorators create foreign keys automatically.
```

Note I'm suggesting this change once, but you'll need to copy it to each overload signature below.

2025-03-25 20:35 UTC, sgarner approved these changes
LGTM :tada:

@yevhen-komarov This is great work, thank you again!

2025-03-25 22:51 UTC, sgarner requested changes
Coveralls has identified a couple of code paths in `EntityMetaDataBuilder.createForeignKeys()` which aren't tested, can you address?

2025-03-26 15:20 UTC, yevhen-komarov commented
🚀Now everything is ready. You can make a review.

2025-03-27 21:02 UTC, sgarner approved these changes

2025-03-28 11:53 UTC, yevhen-komarov commented
I am implementing it for entity schemas. Please wait a bit.

2025-03-29 09:19 UTC, yevhen-komarov commented
I added implementation, documentation and test for entity schemas. Review the changes again.

2025-03-29 12:41 UTC, OSA413 approved these changes

2025-03-29 20:55 UTC, sgarner approved these changes
Thanks for picking up on the missing EntitySchema support @yevhen-komarov !

2025-03-29 20:55 UTC, sgarner commented on test/functional/decorators/foreign-key/wrong city.ts
> +export class WrongCity {
This file appears to have a space in its name `wrong city.ts` - should use kebab-case

2025-04-03 21:22 UTC, merged