Insert rowsAffected in oracle database in delete function
typeorm/typeorm pull request #3547
Opened 2019-01-30 21:04 UTC by RobinsonLuiz

rowsAffected using the delete method with oracle database was returning undefined, these modifications return the number of rows affected in the database.

2019-01-30 21:05 UTC, RobinsonLuiz commented
rowsAffected using the delete function with oracle database was returning undefined, these modifications return the number of affected rows in the database.

2019-02-09 06:24 UTC, pleerock commented on src/driver/oracle/OracleQueryRunner.ts
> +                    ok(result.rows || result.outBinds || result.rowsAffected);
This approach doesn't look good. I suggest to add a third flag paramater to `query` method, something like `fullResult: boolean` (don't like this name however) and make a check here and return some `QueryResult` interface (need to create a new interface) with `rowsAffected` inside as well with all other additional data. Then you just call a method in `delete query runner` with fullResult = true.

Also, can you please implement same for other methods (update and insert)? Also would be really helpful if you can do it for all other drivers as well and we can officially support this feature and add documentation to it.

2019-02-09 06:25 UTC, pleerock commented on src/query-builder/DeleteQueryBuilder.ts
> +                    deleteResult.raw = result.rowsAffected;
and also looks like you need to change `deleteResult.affected` not `deleteResult.raw`. Careful!

2020-10-11 04:45 UTC, imnotjames commented
@RobinsonLuiz are you looking to return to this to continue the work on it?  There's a few open comments that need resolved & conflicts between this change and the master branch.  This also needs tests to be good to bring in.

2020-10-11 04:45 UTC, imnotjames requested changes
This needs tests to verify the behavior works as expected.

2020-11-02 15:50 UTC, imnotjames commented
Thanks for your contribution!  However, without tests that confirm this fixes the correct behavior we cannot accept this pull request.

Once you're able to get back to working on this and add tests which show this corrects the specified behavior please re-open a new PR.

2020-11-02 15:50 UTC, closed without merging