Fix for #3640: Setting Null values in query rather than passing them as query parameters for AbstractSqliteDriver
typeorm/typeorm pull request #3923
Opened 2019-04-01 01:11 UTC by velval

This fixes issues with typeorm when using with NativeScript in Android platform. Underlying sqlite driver for Android requires all query parameter not to be null, so when updating an existing column value with null typeorm should set it directly into the query rather than passing null as one of the query parameters.

https://github.com/typeorm/typeorm/issues/3640

2019-04-01 07:57 UTC, webleaf commented
@velval there are [tslint errors](https://travis-ci.org/typeorm/typeorm/jobs/513914057)

2019-04-02 01:23 UTC, velval commented
Hey @webleaf , I've fixed those tslint errors and all checks seemed have passed now.

2019-04-21 11:52 UTC, pleerock commented on src/query-builder/UpdateQueryBuilder.ts
> +                    } else if ( (value === undefined || value === null) && this.connection.driver instanceof AbstractSqliteDriver ) {
`undefined !== null`. Why do you check for undefined value here?

2019-04-21 11:52 UTC, pleerock commented on src/query-builder/UpdateQueryBuilder.ts
> +                } else if ( (value === undefined || value === null) && this.connection.driver instanceof AbstractSqliteDriver ) {
same here

2019-04-28 12:44 UTC, webleaf commented
I think we could do `value == null`. It checks for `undefined` too.
But (even in this case) set entity field to `undefined` does not produce `UPDATE` query either (looks like it by design in typeorm)
About the fix as a whole, it seems to work for me.

2019-04-28 19:45 UTC, pleerock commented
Im not asking to do `value == null`, Im asking why we need to do more than `value === null`.

> But (even in this case) set entity field to undefined does not produce UPDATE query either (looks like it by design in typeorm)

right, this is why Im asking why this undefined check is needed here

2019-04-29 10:07 UTC, webleaf commented
@pleerock please, make as it would be better

2020-06-19 15:30 UTC, jscti commented
Can this be merged ?

2020-10-14 09:37 UTC, imnotjames requested changes
If this is only affecting native script, why update all SQLite drivers?

2020-10-14 09:41 UTC, imnotjames commented
Given there were unanswered questions, last activity over a year ago & this would negatively impact other drivers I'll be closing it.

I'll be closing this PR but if you ever get time to come back to it please feel welcome to open a new PR addressing the concerns.

2020-10-14 09:41 UTC, closed without merging