Postgres driver generates wrong PK name (with custom schema)
typeorm/typeorm pull request #4063
Opened 2019-04-29 22:46 UTC by XBeg9

*BUG report:* if you use a custom schema name, you will be not able to drop / rename / change your PK constraint. `typeorm` (latest stable version and `next`) doesn’t include schema name inside `createTableSql` method when it creates PKs, but it includes it inside other methods.
*Question here:*
1) If we will fix it inside `createTableSql`, this will fix an issue for new tables, but not for old ones. (`table.name = this.driver.buildTableName(table.name, _this.driver.options.schema);)`)
2) or we will fix it inside other methods (change / delete / update), so we will not use `schema` name for PK namingStrategy (`this.connection.namingStrategy.primaryKeyName(table.name, columnNames);`)

2019-04-30 13:41 UTC, pleerock commented
I've asked @AlexMesser and he told its a wrong solution since constraint name is required to be in the key name. @AlexMesser can you propose different solution?

2019-04-30 13:55 UTC, AlexMesser commented
table schema is required in constraint names to support multi schema functionality. Constraint names must be unique across all schemas. Based on this, the first decision is correct. I assume that problems with synchronization will not arise. Typeorm will just recreate the changed constraints during synchronization. But it needs more investigations.

2019-04-30 15:04 UTC, XBeg9 commented
@AlexMesser I agree, that scheme should be included in both cases. I will try to change my code to reflect your suggestions. And fix several tests.

2020-10-17 20:59 UTC, imnotjames commented on test/github-issues/4063/issue-4063.ts
> +    it("should generate correct PK name", () => Promise.all(connections.map(async connection => {
Can this be made more descriptive of the scenario?

2020-10-17 21:01 UTC, imnotjames requested changes
Tests are failing - can you rebase and fix them?

2020-10-17 21:01 UTC, imnotjames commented on test/github-issues/4063/issue-4063.ts
> +describe("github issues > #4063 [Postgres] Query runner generates wrong PK name (with custom schema)", () => {
Is it possible for this scenario to be placed under `test/functional/query-runner/drop-primary-key.ts`? & the create primary key?

2021-04-10 12:03 UTC, AlexMesser commented
I'm closing this as it's failing and hasn't been updated in a few years. Anyway, thank you for contribution.

2021-04-10 12:03 UTC, closed without merging