fix: wrong query on QueryBuilder containing skip, take and orderBy
typeorm/typeorm pull request #4257
Opened 2019-06-07 20:00 UTC by Hossein-s

QueryBuilder has strange behaviour when it comes to ordering rows.

I couldn't understand why TypeORM breaks fetching rows to two parts😬. first fetching ids and then fetching actual data.

By the way seems does this job wrongly. columns that are needed for ordering (outside of inner query) are not selected and then not available outside it.

Addresses #2736 and #3501.

2019-06-08 15:06 UTC, pleerock commented
try to add some joins and you'll understand why it does so. I don't recommend to change those areas, they are sensitive and hard to review

2019-06-08 15:19 UTC, Hossein-s commented
@pleerock 

Yes it is so harder that it seems😃 By the way it should be fixed somehow, shouldn't? 🤔

2019-06-08 15:33 UTC, pleerock commented
ORM adds order by because it is required, and you must select columns used in order by statement, so consider it as a requirement. If you don't like this requirement consider re-building your query different way.

2019-06-08 15:40 UTC, Hossein-s commented
> ORM adds order by because it is required, and you must select columns used in order by statement, so consider it as a requirement.

I didn't get you. It is a problem in the codes? It does select columns in orderBy and it's obviously a requirement.

2019-06-08 20:26 UTC, Hossein-s commented
It seems I have chosen inappropriate PR message.

Second paragraph describes a question came to my mind.
But I have not changed the behavior of querybuilder in the PR and tried to fix issues occurred with current implementation.

2019-06-08 20:51 UTC, Hossein-s commented
Something is still causing problem for this part. I have the following code but queryBuilder is not escaping ServiceIdSquare.
It's a bug or intended?

```connection.createQueryBuilder()
            .select("Service")
            .from(Service, "Service")
            .addSelect("Service.id * Service.id", "ServiceIdSquare")
            .orderBy("ServiceIdSquare");```

2019-08-05 15:11 UTC, anodynos commented
I can confirm that this nasty bug (we recently discovered it in production) occurs only when `join`, `skip`/`take` & `orderBy` are used together.  The remedy seems to be the painful refactoring of all our queries to use "where exists" structure etc instead of joins, which is pretty awful :-( 

When all these 3 culprits are used, the ORM synthesises a query with this structure:  

```SELECT DISTINCT "distinctAlias".""Entity_alias_id" as "ids_Entity_alias_id"` from (...) ORDER BY "SomeOrderByField" ASC LIMIT 10``` but without adding the `"SomeOrderByField"` in the select clause (and exposing it from the inner query - although I add it manually with the same name). 

Postgres complains that `ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list`. If I manually add  `"SomeOrderByField`" in the failing SQL query it all works fine.

I can't assess if its a "simple fix" or not, but it needs to be fixed... :+1:

2019-09-03 14:19 UTC, anodynos commented
Any updates on this - its breaking a lot of functionality and there's no way around it if we want to use joins :-(

2019-09-17 19:31 UTC, MarKayS commented
> I can confirm that this nasty bug (we recently discovered it in production) occurs only when `join`, `skip`/`take` & `orderBy` are used together. The remedy seems to be the painful refactoring of all our queries to use "where exists" structure etc instead of joins, which is pretty awful :-(
> 
> When all these 3 culprits are used, the ORM synthesises a query with this structure:
> 
> `` SELECT DISTINCT "distinctAlias".""Entity_alias_id" as "ids_Entity_alias_id"` from (...) ORDER BY "SomeOrderByField" ASC LIMIT 10 `` but without adding the `"SomeOrderByField"` in the select clause (and exposing it from the inner query - although I add it manually with the same name).
> 
> Postgres complains that `ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list`. If I manually add `"SomeOrderByField`" in the failing SQL query it all works fine.
> 
> I can't assess if its a "simple fix" or not, but it needs to be fixed... 👍
> 
> FYI: I don't have any complex order by (only a single one), only one single join, and it fails with just `skip = 0` and `take = 10`.

We ran into this specific issue and for now resolved it by using limit and offset instead of skip and take. So far it seems to work with non-complex joins and order bys (two left joins and order bys on those nested columns).

2020-03-09 15:56 UTC, anodynos commented
Any updates on this issue / PR? It's been 6 months and we're facing major problems using TypeORM because of this...

2020-07-16 10:29 UTC, rostamiani commented
Still waiting for a merge...

2020-10-17 21:06 UTC, imnotjames requested changes
The tests aren't comprehensive enough.  With various joins this code will break - so can we add those to the tests per the previous comment by pleerock?  It sounds like they caused problems and broke some functionality so we need to verify that's working first.

2020-10-17 21:06 UTC, imnotjames commented
> Please merge this request if it works. Anyone tested?

It seems to fix some scenarios and breaks others.

2020-10-20 06:18 UTC, Hossein-s commented
> The tests aren't comprehensive enough. With various joins this code will break - so can we add those to the tests per the previous comment by pleerock? It sounds like they caused problems and broke some functionality so we need to verify that's working first.

Thanks for reviewing this PR.

Actually I couldn't find any problem as all the project tests were passing. Would you give some queries or (guide me to build them) that this PR will break so that I can investigate more and update PR to consider them too?

2021-06-08 06:22 UTC, manavjaiswal commented
Having the same issue. SQL fails with Unknown column 'distinctAlias.xxx_id' in 'field list'. 
I am using querybuilder with order by and pagination. Is there any updates on this please. I request to get this resolved soon. Thanks.

2021-06-17 06:10 UTC, imnotjames commented
Here's an extra test which shows that this PR breaks other cases.

```
                // create some users
      
      
                const user1 = new User("user 1");
      
      
                const user2 = new User("user 2");
      
      
                const user3 = new User("user 3");
      
      
        

      
      
                // create some services
      
      
                const service1 = new Service("service 1 for user1", user1);
      
      
                const service2 = new Service("service 2 for user1", user1);
      
      
                const service3 = new Service("service 1 for user2", user2);
      
      
                const service4 = new Service("service 1 for user3", user3);
      
      
                const service5 = new Service("service 2 for user3", user3);
      
      
        

      
      
                // store entities
      
      
                await connection.manager.save([user1, user2, user3, service1, service2, service3, service4, service5]);
      
      
        

      
      
                // create complex QueryBuilder
      
      
                const queryBuilder = connection.getRepository(User).createQueryBuilder("user");
      
      
                queryBuilder
      
      
                    .leftJoinAndSelect("user.services", "service")
      
      
                    .skip(0)
      
      
                    .take(3)
      
      
                    .addOrderBy("service.title", "DESC");
      
      
        

      
      
                console.log(queryBuilder.getQuery());
      
      
        

      
      
                const users = await queryBuilder.getMany();
      
      
        

      
      
                // should return services for user1 and user3
      
      
                expect(users).to.have.length(3);
      
      
        

      
      
                // should be in right order
      
      
                expect(users).to.eql([
      
      
                    user1,
      
      
                    user2,
      
      
                    user3,
      
      
                ]);
 ```

2021-07-05 22:12 UTC, closed without merging