fixed incorrect WHERE caused by type as primary key in STI
typeorm/typeorm pull request #4275
Opened 2019-06-11 19:18 UTC by aolvictim

This is a potential fix for the issue https://github.com/typeorm/typeorm/issues/4252

Basically it checks if the discriminator value is present in the entity, if not, add it.

2019-06-16 14:30 UTC, YegorZaremba commented
It'll be better if you write a tests for this case

2019-06-16 14:58 UTC, pleerock commented
First of all we need to narrow down issue scope. Is this issue only when you use STI? Can we confirm it by having a test for this case (your issue without STI, the most simple case). If issue exist then this fix isn't correct. The reason I ask is because we need to fix a source of problem, which is hard to find in this case.

2020-10-17 21:09 UTC, imnotjames requested changes
This needs tests to confirm that the behavior you expect from this code is exhibited.

2020-10-17 21:11 UTC, imnotjames commented on src/metadata/EntityMetadata.ts
> +            fullEntity[this.discriminatorColumn.databasePath] = this.discriminatorValue;
Not sure I understand why you've assigned this variable and then are changing the prop in this variable.  Could you explain it to me?

If it's an object it's the same object in both variables - you haven't cloned it - so you might as well just `entity[this.discriminatorColumn.databasePath] = this.discriminatorValue;`

2021-05-29 16:05 UTC, AlexMesser commented
Closing as there is no answer from OP.

2021-05-29 16:05 UTC, closed without merging