Fix query builder crashing when using object in .where inside Brackets
typeorm/typeorm pull request #4337
Opened 2019-06-21 13:23 UTC by Ephys

This is an attempt at fixing #3685 where the following piece of code

```typescript
const generatedSql = entityManager
    .createQueryBuilder()
    .from(Product, 'Product')
    .where(new Brackets(qb => qb.where({ id: 1 })))
```

would crash because the QueryBuilder could not determine the alias to use for `id`

2019-06-30 15:05 UTC, pleerock commented
This small functionality got too complex in my opinion.

2019-08-23 11:18 UTC, tonivj5 commented
Any progress?

2019-10-31 00:28 UTC, viczam commented
can we get this merged?

2020-10-18 21:03 UTC, imnotjames requested changes

2021-04-24 09:39 UTC, AlexMesser commented
Superseded by #5659. Anyway, thank you for contribution.

2021-04-24 09:39 UTC, closed without merging