add column comment support for for postgres
typeorm/typeorm pull request #4461
Opened 2019-07-18 17:59 UTC by nionoku

Adding a comment to a column when creating a column for postgres.

Related #4359

2019-07-23 13:34 UTC, nionoku commented
Fix test, comments are now added when creating a table in PostgreSQL.

2019-08-13 16:35 UTC, rmainseas commented
Just to clarify the title of the PR...


Postgres column comments are already supported. They just don't work. But it's cool that you have a PR to fix this, thank you!

2019-08-14 06:15 UTC, nionoku commented
> Just to clarify the title of the PR...
> 
> Postgres column comments are already supported. They just don't work. But it's cool that you have a PR to fix this, thank you!

Indeed, but the moment I was thinking about the name, there was a slightly different thought in my head. Thanks for comment.

2019-08-14 12:52 UTC, rmainseas commented
Yeah, not trying to be pedantic - I just thought it was worth pointing out :) <3

2019-08-21 23:19 UTC, rmainseas commented
Also, just to add - I've noticed that column comments actually already work (sort of) with postgres.....if you create a column it doesn't add the column comment in the migration. But if you somehow change something about that column (the length, the type etc.) the changes written into a migration also include the column comment.

2019-08-22 07:52 UTC, nionoku commented
> Also, just to add - I've noticed that column comments actually already work (sort of) with postgres.....if you create a column it doesn't add the column comment in the migration. But if you somehow change something about that column (the length, the type etc.) the changes written into a migration also include the column comment.

Yes, a comment for the column was added when changing the model fields.
My PR adds a comment to the column when creating the table :)

2019-08-29 09:19 UTC, nionoku commented
@rmainseas hello! Thank you for your attention to the question, regarding the attached issue #3357, I created a small repository, as typeorm I used my fork accordingly, and tested: created an entity, synchronized it with the database, conducted a test: the first module was executed, the second failed (as expected), then I changed the length of the field in the entity and repeated synchronization with the database, and repeated testing - all tests have been passed. That is, the comment is saved (by the way, this functionality is not included in my PR).
https://github.com/nionoku/typeorm-field-options-test

2020-02-04 18:44 UTC, jjosef commented
This is really basic and simple, any reason it is not being merged?

2020-02-20 13:11 UTC, AlexMesser commented on src/driver/postgres/PostgresQueryRunner.ts
> +            downQueries.push(new Query(`COMMENT ON COLUMN ${this.escapePath(table)}.${column.name} IS '${column.comment}'`));
`column.name` should be escaped here

2020-02-20 13:11 UTC, AlexMesser commented on src/driver/postgres/PostgresQueryRunner.ts
> +            .forEach(it => sql += ` COMMENT ON COLUMN ${this.escapePath(table)}.${it.name} IS '${it.comment}';`);
`it.name` should be escaped here

2020-02-20 13:21 UTC, AlexMesser commented
@nionoku we also need to obtain information about column comments from database and put it into ColumnMetadata for subsequent schema synchronization, like we did it with column charset and collation for example. e.g. in your current PR comment won't be applied on existing column. It also won't be removed once you remove comment from the decorator (or change existing comment)

2020-10-08 06:07 UTC, imnotjames commented
Any luck on addressing these issues?  Without pulling it into column metadata, synchronize will stop working.

Can you rebase this & fix conflicts, as well?

2020-10-12 18:43 UTC, imnotjames commented
Related issue #3360

2020-10-17 16:38 UTC, imnotjames requested changes
This needs to update the change detection code to handle checking for comment changes.

Also comments need to be escaped somehow

2020-10-19 16:45 UTC, closed without merging