Ensure we don't have duplicated columns in update (Fixes #2651)
typeorm/typeorm pull request #6501
Opened 2020-08-02 17:10 UTC by kieranajp

Hi,

I noticed that an erroneous update query was being generated in my application:

```
ERROR:  multiple assignments to same column "column_id"
STATEMENT:  UPDATE "tasks" SET "column_id" = $2, "column_id" = $3, "task_position" = $4 WHERE "id" IN ($1)
```

I did a bit of digging and was able to narrow it down to this `updatedColumns` array not having a uniqueness check.

![image](https://user-images.githubusercontent.com/681426/89128093-6f706600-d4f3-11ea-9ec2-43e95db28af4.png)

I'm not sure exactly what it is about my entity structure that triggers this, but I added a sanity check anyway. Please let me know if there's anything I can do to help get this merged.

Cheers,
--Kieran

2020-10-03 00:19 UTC, imnotjames commented
Won't this fail with having too many parameters, then?

Also, could you rebase this against master so we can see the tests running? :)

2020-10-07 09:40 UTC, kieranajp commented
Good question - honestly I don't remember. We ended up switching away from Node for the backend of this particular application so I'm afraid I don't have a way to repro this anymore.

Rebase incoming anyway.

2020-10-18 16:26 UTC, imnotjames requested changes
This needs tests to confirm the behavior.  If you can't preproduced it that might be an issue.

2020-12-02 15:23 UTC, HctrM commented
I've also encountered this issue with Postgres driver and saving a relation with the foreign key ref. Looking forward to bug fix.

2021-06-16 05:44 UTC, imnotjames commented
This PR has been stale a while without tests.  We can't merge in code without confirming it resolves the underlying issue.

Closing out.

2021-06-16 05:44 UTC, closed without merging