test: EntityManager.insert() with explicit primary keys (#7094)
typeorm/typeorm pull request #7095
Opened 2020-11-21 16:43 UTC by AdrianDC

### Description of change

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2020-11-21 20:34 UTC, nebkat requested changes

2020-11-21 20:34 UTC, nebkat commented on package.json
> +    "uuid": "^8.3.1"
Should use the internal uuid generation:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/util/RandomGenerator.ts#L149

2021-06-15 07:41 UTC, imnotjames commented on test/github-issues/7094/issue-7094.ts
> +        console.log(items);
Can you remove this `console.log`

2021-06-17 04:26 UTC, imnotjames approved these changes

2021-06-17 04:26 UTC, imnotjames commented
This is still a draft - are you not looking to have it merged?

2021-06-17 06:51 UTC, AdrianDC commented
The original issue is detailed on issue https://github.com/typeorm/typeorm/issues/7094.

This PR is meant to reproduce the issue, but as I stated there, I could not get it reproduced back then,
unlike the same code being used in production since version "0.2.26".

2021-06-19 14:07 UTC, imnotjames commented
So it doesn't replicate the issue - should we close it instead?

2021-07-05 15:48 UTC, closed without merging