Add relation option "createForeignKeyConstraints"
typeorm/typeorm pull request #7112
Opened 2020-11-26 15:29 UTC by alpharder

### Description of change

Fixes #3120 by adding a new relation option "createForeignKeyConstraints"

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2020-11-27 02:39 UTC, nebkat requested changes
From what I can tell `ForeignKeyMetadata`, other than to create `TableForeignKeys`, is only used to pass the `joinColumns` and `inverseJoinColumns` to this function:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/metadata/RelationMetadata.ts#L490-L500

This function is only called in two places:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/metadata-builder/EntityMetadataBuilder.ts#L195
https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/metadata-builder/EntityMetadataBuilder.ts#L130-L131

Instead of having `ForeignKeyMetadata`s that aren't created in DB, why don't we eliminate them at this stage and pass `joinColumns` and `inverseJoinColumns` into a separate function (perhaps rename it to `registerJoinColumns()`) and push foreign keys into `relation` the same way they are pushed into `entityMetadata` above? After all if foreign keys aren't in the database, should we really ever call them foreign keys at all?

2020-11-30 15:15 UTC, acepace commented
@alpharder what help do you need to finish this PR? I'm also blocked on this

2020-11-30 16:08 UTC, nebkat commented
@acepace I've described some changes I that I think need to happen, but it is still usable in its current form. If you urgently need this I suggest you fork and cherry-pick what is here. Otherwise if @alpharder has not begun you could try to make those changes yourself and submit a new PR, but it's best to wait a while first. You can :+1: the PR to give it more attention.

2020-11-30 22:15 UTC, alpharder commented
@acepace Well, this is 100% usable as is, because the patched version of TypeORM is used at our production for like 6 months already.

However, I haven't dived too much into TypeORM's internals because we've in the middle of migrating to MikroORM and most probably @nebkat 's comments should be taken into account before merging this into the mainline. 

I think I will finish with this until the end of the week, but another question is – how time much will it take to merge it after changes I'll make.

If you need to use it right now I suggest you to:
1) Install the latest version of TypeORM (or update an existing one) and commit changes; 
2) Clone my branch containing the fix;
3) Build it manually;
4) Put the build result files into corresponding typeorm directory at your project's node_modules
5) Use patch-package to make a permanent patch

2020-12-01 07:49 UTC, acepace commented
That's awesome.
I'll see about fixing @nebkat comments and if so will open a joint PR (like, joint commit history, not sure how to give us both permissions).

2021-01-11 14:06 UTC, pleerock commented
This PR looks like a good start to fix #3120 . Does anyone want to finish it? If no, I'll have to close it for now.

2021-01-15 14:16 UTC, Saniol commented
> This PR looks like a good start to fix #3120 . Does anyone want to finish it? If no, I'll have to close it for now.

I finished changes and (as I couldn't update this one) submitted them in new PR - #7277

2021-01-22 00:21 UTC, nebkat commented
Fully completed in #7277, discussion can move there.

2021-02-02 14:55 UTC, pleerock commented
Closing in favor of #7277

2021-02-02 14:55 UTC, closed without merging