fix: Make QueryRunner do not generate duplicate create enum query
typeorm/typeorm pull request #7564
Opened 2021-04-12 18:33 UTC by 5d-jh

### Description of change

This issue fixes #7523 by storing built enum names in set class property.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change N/A
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2021-06-11 06:11 UTC, MrBacony commented
"Documentation has been updated to reflect this change N/A"

is there a point in the documentation which should be updated?

2021-06-11 08:13 UTC, 5d-jh commented
@MrBacony As far as I know of there isn't any. That's why I marked as N/A.

2021-06-14 10:09 UTC, MrBacony commented
@5d-jh ok good to know.

Maybe we have to check in your code, if all duplicate Enums have the same Entries.

I hope this PR will be merged soon.

2021-07-11 07:14 UTC, imnotjames requested changes
I don't think this is a complete solution.

Wouldn't this not handle the case where you aren't doing this all at once?

Like if you create a new table that shares the enum - but not at the same time as the first one.

Then it would fail again.

Is it possible to add a test for that case?

2021-07-12 17:56 UTC, 5d-jh commented
@imnotjames

Come to think about it, this PR isn't a good solution to resolve the issue.

I think registering all of enums in connection options, then referencing them by name would be a better solution in terms of maintainability. Example below.

```typescript
import SomeEnum from './some-enum';

createConnection({
  enums: [{
    name: 'some_enum',
    enum: SomeEnum,
  }]
})
```

```typescript
@Entity()
class SomeEntity {
  @Column({
    type: 'enum',
    enumName: 'some_enum',
  })
  someEnumField: SomeEnum;
}
```

Please let me know if this might be a better solution.

2021-09-23 04:02 UTC, 5d-jh commented
Closing this PR since there is better solution #8161

2021-09-23 07:09 UTC, 5d-jh commented
* `same name and different values within one migration` -> abort migration and throw error
* `same name and same values within one migration && different values with already defined in database` -> perform alter type

Will this flow solve the issue? (If this is accepted, would specify this behavior in documentation)

2022-02-19 10:45 UTC, AlexMesser commented
Finally I was able to review this PR.

Right now we have `hasEnumType` call inside `createTable` which should not be there, because `createTable` should not have any database calls to work properly with both runtime sync and migration generation. According to proper schema sync design we should first load all necessary data from the db, then execute sync based on comparison of db schema and schema collected from entity metadatas.

So, we actually need to re-implement current enum sync approach before we can properly fix this issue.

I have a suggestion on how to change the current implementation:

1. Introduce a new decorator called `@CustomType` which can be used on entities:

```ts
@CustomType({ name: `foo_enum`, type: "enum", value: FooEnum })
class ParentEntity {
}
```

2. remove `enumName` from ColumnOptions and introduce custom types support:

```ts
@Column(`foo_enum`)
foo: FooEnum;
```

3. if user don't want to create a custom type we can still specify "inline" enum but without name (and if we have two usages of the same enum, ORM automatically create us two enum types with different generated names even through with the same values - it's expected behaviour until we introduce a `@CustomType`

4. inside `RdbmsSchemaBuilder` we sync custom types separately (just like how we do it for indices, fks, etc.)

```ts
        await this.dropOldViews();
        await this.dropOldForeignKeys();
        await this.dropOldIndices();
        await this.dropOldChecks();
        await this.dropOldExclusions();
        await this.dropCompositeUniqueConstraints();
        await this.renameColumns();
        await this.createNewTables();
        await this.dropRemovedColumns();
        await this.dropCustomTypes() // NEW
        await this.createCustomTypes() // NEW
        await this.addNewColumns();
        await this.updatePrimaryKeys();
        await this.updateExistColumns();
        await this.createNewIndices();
        await this.createNewChecks();
        await this.createNewExclusions();
        await this.createCompositeUniqueConstraints();
        await this.createForeignKeys();
        await this.createViews();
```

Unfortunately re-implementation will take lot of time, and we have to postpone it to 0.4.0

2022-02-19 10:54 UTC, AlexMesser commented
Unfortunately I have to close this PR because we should implement it slightly different... Closing in favor of #8672

2022-02-19 10:54 UTC, closed without merging