Upgrade version of mssql to fix a bug of date with mssql driver (tedious)
typeorm/typeorm pull request #7600
Opened 2021-04-28 17:31 UTC by v1d3rm3

### Description of change

Hello! I'm sending a PR to solve a problem in Date described here https://github.com/tediousjs/tedious/issues/1249 and here https://github.com/tediousjs/node-mssql/issues/1223.  Unfortanalety, it'll not be a version to solve the problem in `mssql v6`, so i'm sending this upgrade for `next´ branch, because i'm using this version in my job a long time motivated by this issue (https://github.com/typeorm/typeorm/issues/4270).

In PR, i did the following things (sorry for not separate them). First i upgraded mssql version to v7. Then i correct the way to send name parameters to mssql (tedious aparently not accept name as numbers, only strings). When running the tests, i identified two problems. The first about dates, but it was occurring causa a wrong way to instantiate iso date string with date object. The second error is something i did not touched, something about `sinon` and `logs`. I skipped this test.

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2021-05-25 10:21 UTC, v1d3rm3 commented
@AlexMesser , @pleerock. Some help here, please?

2021-05-29 15:52 UTC, AlexMesser commented
Thank you for contribution.

Since it's not clear when `@next` is going to be merged into `master` right now, it's better if you do this PR against master. If its a breaking change we need to add additional code to make it backward-compatible. Also please remove all formatting from the PR to make it easier to review this PR. Thank you.

2021-05-29 17:01 UTC, v1d3rm3 commented
In my job, we're using the `next` branch, and we're awaiting for these changes. We only follow what collaborators said before https://github.com/typeorm/typeorm/issues/4270#issuecomment-501207213. We cannot use master code cause of error that exists until now. I think 

Changes are identified by commits: https://github.com/typeorm/typeorm/pull/7600/commits/98671c895a6070a137937411cae26372a1ed3b6c and https://github.com/typeorm/typeorm/pull/7600/commits/f2e535cf44f568c555401e54e74aa96e8edd863a.

I decide to fix linting as format, because it's present by pr checklist.

Can you merge this in `next`? After that, i can make cherry picks to do changes in master.

2021-06-18 04:18 UTC, imnotjames requested changes
Remove the formatting changes.

2021-06-18 04:22 UTC, imnotjames commented on src/util/DateUtils.ts
> +        /**
If you want to include this change, it's better to do so in a separate r

2021-06-24 16:14 UTC, closed without merging