Pass the entity through on afterUpdate
typeorm/typeorm pull request #7724
Opened 2021-06-09 06:27 UTC by francescoferraioli

### Description of change

Similar to #5443, just for the afterUpdate subscribers.

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2021-06-18 03:50 UTC, imnotjames approved these changes
This makes sense to me and the tests look good.

2021-06-18 04:00 UTC, imnotjames requested changes

2021-06-21 07:39 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
in an update you can pass in a partial entity, only the properties you want updated.

2021-06-21 13:48 UTC, imnotjames commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
I understand.  However, the definition of `UpdateEvent` REQUIRES the actual entity.  Not the partial.

2021-06-21 23:54 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
Yeah I agree that the type is not strictly correct. I think the problem is that the `UpdateEvent` is called both when you use `save` and when you use `update`. In the case of `save` it's the full entity but in the case of `update` it's a partial.

The same could be said about the existing `beforeUpdate` subscriber as that is currently being passed a partial entity but the type doesn't reflect that.

As we currently are doing the exact same thing for `beforeUpdate`, I think it's safe to do it for `afterUpdate` and fixing the type could be done separately.

2021-06-22 15:19 UTC, imnotjames commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
If that's the case, can you update the types to match that?

2021-06-22 23:30 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
I have corrected the type at https://github.com/typeorm/typeorm/pull/7783

2021-06-22 23:31 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
I have done it as a seperate PR for a number of reasons:
- The type fixing spans more than just the `afterUpdate`
- It is a breaking change whilst this is not

I think PRs should be very targeted at fixing one thing at a time :)

2021-06-28 22:35 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
@imnotjames - is there any further reason not to accept this PR?

2021-07-05 02:06 UTC, francescoferraioli commented
@imnotjames - is there any further reason not to accept this PR?

2021-07-11 22:54 UTC, francescoferraioli commented on test/github-issues/2809/subscriber/PostSubscriber.ts
> +            event.entity["title"] = "set in subscriber after updated";
@imnotjames - now that https://github.com/typeorm/typeorm/pull/7783 is in, can we please also accept and merge this one?

2021-07-14 21:28 UTC, imnotjames approved these changes

2021-07-15 09:17 UTC, merged