@UpdateDateColumn support for Upsert
typeorm/typeorm pull request #9064
Opened 2022-06-02 06:44 UTC by zevstravitz

### Description of change

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2022-06-28 14:43 UTC, pleerock commented
Looks like tests are failing.

2022-11-09 16:28 UTC, Thore1954 commented
Any updates on this?

2022-11-09 16:35 UTC, Thore1954 commented
@pleerock I manually tested this fork and it's working. I think the tests are failing because they don't expect the update date column to be updated!
My current work around is:
```ts
await repository.upsert(
    [
        { externalId: "abc123", firstName: "Rizzrak", updatedAt: () => `now()` },
        { externalId: "bca321", firstName: "Karzzir", updatedAt: () => `now()` },
    ],
    ["externalId"],
)
```
But it only works on postgres so would love to get rid of it as soon as possible.

2022-11-17 12:36 UTC, Thore1954 commented
Actually, there's currently no assertion on the update date column in tests:
https://github.com/typeorm/typeorm/blob/85fa9c6e7df1a0e3ba8c95d64d9b2a6ab464e0e0/test/functional/repository/basic-methods/repository-basic-methods.ts#L500-L505
Why are the tests failing? @zevstravitz @pleerock

2022-12-06 10:31 UTC, Thore1954 commented
I found out the problem is the `skipUpdateIfNoValuesChanged` option is not respected by this change.
One solution is to exclude update date column from the condition:
https://github.com/typeorm/typeorm/blob/0d72317b3db3f93ce9d4c2f6f027c7486bbed08b/src/query-builder/InsertQueryBuilder.ts#L542-L551
Should be changed to:
```ts
                    query += overwrite
                        .filter(column => !(this.expressionMap.mainAlias!.hasMetadata && this.expressionMap.mainAlias!.metadata.findColumnWithDatabaseName(column)!.isUpdateDate))
                        .map(
                            (column) =>
                                `${tableName}.${this.escape(
                                    column,
                                )} IS DISTINCT FROM EXCLUDED.${this.escape(
                                    column,
                                )}`,
                        )
                        .join(" OR ")
```

2022-12-06 19:57 UTC, Thore1954 requested changes

2022-12-06 19:57 UTC, Thore1954 commented on src/entity-manager/EntityManager.ts
> +                    col.isUpdateDate),
When `skipUpdateIfNoValuesChanged` option is set, it shouldn't add update date column otherwise it will update even when nothing has changed.

2022-12-08 07:24 UTC, Thore1954 commented
@zevstravitz thanks for the PR! Unfortunately, this wouldn't work because when `skipUpdateIfNoValuesChanged` option is set it won't skip update when nothing has changed.

2023-02-06 10:42 UTC, AlexMesser commented
Closing due to inactivity and failing tests. Feel free to submit a new PR.

2023-02-06 10:42 UTC, closed without merging