Feature/mongodb populate/master
typeorm/typeorm pull request #9494
Opened 2022-10-25 04:24 UTC by mrgoonie

- refactor MongoEntityManager, use "aggregate" instead of "find" to utilize "$lookup" for populating columns
- add test: `functional/mongodb/basic/relations` to test mongodb querying with "relations"

Closes: #655

### Description of change

Implement a "relations" feature of MongoDB query (just like "populate" in Mongoose)
It should close the issue #655 after 5 years of waiting :)
Add some examples to the documentation of MongoDB.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #655`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2022-10-28 03:56 UTC, hghammoud commented
can we please accept this PR? we all been waiting for so long for this.

2022-10-28 06:18 UTC, hghammoud commented
@mrgoonie I check out your branch and built it. I used yalc to add it locally. Can you please give a more concrete example of nested lists as the relations is not populating the object

```
import { Page } from 'src/page/entities/page.entity';
import { Column, Entity, ObjectID, ObjectIdColumn } from 'typeorm';

@Entity()
export class Namespace {
    @ObjectIdColumn()
    _id: ObjectID;

    @Column()
    label: string = 'Untitled';

    @Column()
    icon: string;

    @ObjectIdColumn({ name: "pages", array: true })
    pages: ObjectID[] | Page[];
}
```
```
import { Namespace } from 'src/namespaces/entities/namespace.entity';
import { Column, Entity, ObjectID, ObjectIdColumn } from 'typeorm';

@Entity()
export class Page {
    @ObjectIdColumn()
    _id: ObjectID;

    @Column()
    title: string = 'Undefined';

    @Column()
    isGroup?: boolean = false;

    @Column()
    markdown?: string = '';

    @ObjectIdColumn({ name: "namespace" })
    namespace?: ObjectID | Namespace;
}
```
```
  @Post()
  async create(@Body() createNamespaceDto: CreateNamespaceDto) {
    let page = new Page();
    page = await this.pageService.create(page);

    let nameSpace: Namespace = CreateNamespaceDto.toNamespace(createNamespaceDto);
    nameSpace.pages = [
      page._id
    ];
    nameSpace = await this.namespacesService.create(nameSpace);

    return await this.namespacesService.findOne(nameSpace._id.toString());
  }
```
```
  findOne(id: string) {
    return this.namespaceRepository.findOne({
      relations: {
        pages: true,
      },
      where: { _id: new ObjectId(id) } as any
    });
  }
```

the result of the the findOne is an empty array... what am I doing wrong? ty.

2022-10-28 07:15 UTC, mrgoonie commented
hey @hghammoud, in "Namespace" entity, change your column decorator "name" to "page" instead of "pages", since it will populate from "Page" collection.

Like this:
```
@ObjectIdColumn({ name: "page", array: true })
pages: ObjectID[] | Page[];
```

then it should work as expected

2022-10-28 12:11 UTC, hghammoud commented
I didnt test further then this case but that did the trick. I ll tell you if other issues arise. ty.

2022-11-01 09:09 UTC, hghammoud commented
It worked. I will be testing further and give you feedback if something is off.

2022-11-22 23:31 UTC, gastonmorixe requested changes

2022-11-22 23:31 UTC, gastonmorixe commented on docs/mongodb.md
> +     ** This means it's an referenced ObjectId of a {User} in "user" collection.
```suggestion
     ** This means it's a referenced ObjectId of a {User} in "user" collection.
```

2022-11-22 23:31 UTC, gastonmorixe commented on test/functional/mongodb/basic/array-columns/mongodb-array-columns.ts
> +                console.dir(loadedUpdatedPost)
```suggestion
```

2022-12-03 14:22 UTC, pleerock commented
I need mongodb users review & approval on this PR.

2023-02-09 04:49 UTC, mrgoonie commented
I've made another pull request to fix some issues: https://github.com/typeorm/typeorm/pull/9767

Cheers,

2023-04-15 04:39 UTC, dmitrye commented
What's the latest here? 

I'm using an aggregateEntity workaround for the time being to populate the child object. 
```

export class UserLogin extends CommonEntityFields {
    ....

@Column((type) => User)
    user: User;

 ....
 }
 

``` 
And the service:

```
this.userLoginRepository.aggregateEntity([
            {
                $lookup: {
                    from: 'user',
                    localField: 'user',
                    foreignField: '_id',
                    as: 'user',
                }
            },
            {
                "$unwind": {
                    "path": "$user",
                    "preserveNullAndEmptyArrays": true
                }
            },
            {
                $match: filter
            }
        ]).toArray();
```

But this will become cumbersome to use Aggregate queries everywhere just to merge the relationship data. 
 
 TL;DR
The better Mongo approach is to avoid $lookups in favor of data duplication whenever possible. Things that can be considered snapshots in time: Events, reports, etc, should self contain everything they need from the time of the activity.

2023-04-15 09:08 UTC, pleerock commented
I'm not sure if this PR is still valid, because @mptr just implemented mongodb v5 support and there are lot of conflicts right now. Please create a new PR on top of the latest changes and wait for the community review.

2023-04-15 09:08 UTC, closed without merging

2023-04-15 20:09 UTC, dmitrye commented
@pleerock Can you confirm that the PR for mongo v5 also addresses relationships? If not, then this issue should remain open and be dependent on https://github.com/typeorm/typeorm/pull/9778 being addressed first. 

The purpose of this ticket was to enable Mongo relationships for OneToOne, OneToMany, etc -> and general use case when you have Entity attributes that are lookups into other collections. Which is different from supporting v5 changes.

2023-04-16 00:53 UTC, pleerock commented
no, I just said that this PR isn't valid because there were many conflicts with the new changes on this PR.

2023-08-09 22:13 UTC, angelhdzmultimedia commented
Can someone provide info about if this is already possible?

```ts
@Entity({name: 'profiles'})
class Profile {
  ...someFields
}

@Entity({name: 'users'})
class User {
 ...someFields
 @ObjectIdColumn({name: 'profiles'})
 profile: Profile | ObjectId
}
```

Usage:

```ts
const newUser = this._userRepository.create(registerData)
    const newProfile = this._profileRepository.create({
      displayName: registerData.displayName,
      role: 'user',      
    })
    const createdProfile = await this._profileRepository.save(newProfile, {reload: true})
    const createdUser = await this._userRepository.save(newUser, { reload: true })
    createdUser.profile = createdProfile
    return createdUser
```

And then:

```ts
const user: User | null = await this._userRepository.findOne({
      where: {
        email: loginData.email,
      },
      relations: {
        profile: true,
      }
    })
```

Tried with `relations: ['profile']`.