fix: resolve issue EventSubscribers beforeInsert and afterInsert missing data for junction tables
typeorm/typeorm pull request #9976
Opened 2023-04-22 23:55 UTC by Ainias

### Description of change

Fixes #9974

When data is inserted into a junctionTable (through updating Many-To-Many-Relations) the EventSubscriber's beforeInsert and afterInsert methods are called, but without data. This MR changes that.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

2023-04-23 00:00 UTC, Ainias commented
I'm a little bit unsure if it is the best way to use the entity field that already exists. I used it because this is the normal object that is holding the data inside the listeners. If needed, I can add a new field to the InsertEvent and save the infos there.

2023-04-23 00:22 UTC, spotykatch requested changes
I need to go to sleep. So just superficially. Maybe everything else is ok 😄

2023-04-23 00:22 UTC, spotykatch commented on src/persistence/Subject.ts
> +    createValueSetAndChangeMapsWithoutValues() {
What does this return?

2023-04-23 00:22 UTC, spotykatch commented on package-lock.json
This file is not needed

2023-04-23 00:55 UTC, spotykatch commented
Yeah. I told you about cascade stuff. That is very buggy.

2023-04-23 09:15 UTC, Ainias commented on src/persistence/Subject.ts
> +    createValueSetAndChangeMapsWithoutValues() {
added return type annotations

2023-04-23 09:15 UTC, Ainias commented on package-lock.json
reverted the changes to package-lock.json

2023-04-23 09:40 UTC, Ainias commented
I don't have access to Oracle Database and cannot create a free trial, as a credit card is needed (In germany you can live very good without one). Someone else has to check why the test is not running through

2023-04-26 11:40 UTC, spotykatch requested changes
Please make it more readable for newcomers

2023-04-26 11:40 UTC, spotykatch commented on src/persistence/Subject.ts
> +    ] {
Maybe you should define a Result type for that? Explanation down there...

2023-04-26 11:40 UTC, spotykatch commented on src/persistence/SubjectExecutor.ts
> +                        subject.createValueSetAndChangeMapsWithoutValues()[0],
It is hard to understand what is createValueSetAndChangeMapsWithoutValues() index zero. I mean, that's open source. How would you feel, if you find stuff like that?

2023-05-09 10:44 UTC, pleerock commented
I understood your motivation, but not sure if I want to have such feature in exist codebase. Need to think more about it.

Btw, your test is failing.

2023-08-17 09:02 UTC, hinogi approved these changes
LGTM

2024-01-02 10:04 UTC, pleerock commented
Closing for now.

2024-01-02 10:04 UTC, closed without merging